perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-and\-2nd\-declension\-adjectives\-ā\-o\-stems"/"adjective-declensions.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-and\-2nd\-declension\-adjectives\-genitive\-īus\-dative\-ī"/"adjective-declensions.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-and\-2nd\-declension\-adjectives\-stems\-ending\-ro"/"adjective-declensions.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-conjugation"/"conj14.htm#sect18"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-declension\-greek\-nouns"/"noun-declensions.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/1st\-declension\-stem\-paradigm\-and\-gender"/"noun-declensions.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/2nd\-conjugation"/"conj15.htm#sect19"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/2nd\-declension\-special\-forms"/"noun-declensions.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-conjugation"/"conj16.htm#sect20"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-conjugation\-io\-verbs"/"conj18.htm#sect22"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-adjectives\-classification\-and\-paradigms"/"adjective-declensions.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-gender"/"noun-declensions.htm#sect21"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-greek\-nouns"/"noun-declensions.htm#sect20"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-irregular\-nouns"/"noun-declensions.htm#sect18"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-i\-stems"/"noun-declensions.htm#sect13"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-liquid\-and\-nasal\-stems\-n"/"noun-declensions.htm#sect12"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-mixed\-i\-stem"/"noun-declensions.htm#sect16"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-mute\-stems\-m\-f"/"noun-declensions.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-mute\-stems\-n"/"noun-declensions.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-pure\-i\-stem\-n"/"noun-declensions.htm#sect15"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/3rd\-declension\-pure\-i\-stems\-m\-f"/"noun-declensions.htm#sect14"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/4th\-conjugation"/"conj17.htm#sect21"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/4th\-declension\-stem\-paradigm\-and\-gender"/"noun-declensions.htm#sect22"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/5th\-declension\-case\-forms"/"noun-declensions.htm#sect26"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/5th\-declension\-stem\-paradigm\-and\-gender"/"noun-declensions.htm#sect25"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/adverbs"/"syntax.htm#sect16"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/agreement"/"syntax.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/agreement\-nouns"/"syntax.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/agreement\-nouns\#apposition"/"syntax.htm#282"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/agreement\-nouns\#predicate\-noun\-adjective"/"syntax.htm#predicate-noun-adjective"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/alphabet"/"pronunciation.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/antequam\-and\-priusquam"/"subordinate-clauses.htm#sect11"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/cardinal\-and\-ordinal\-numbers"/"numerals.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/case\-endings\-five\-declensions"/"inflection.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/causal\-clauses"/"subordinate-clauses.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classes\-numerals"/"numerals.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classification\-adverbs"/"adverbs.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classification\-conditions"/"conditionals.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classification\-"/"pronunciation.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classified\-lists\-verbs\-1st\-and\-2nd\-conjugations"/"conj29.htm#sect33"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classified\-lists\-verbs\-3rd\-conjugation"/"conj30.htm#sect34"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/classified\-lists\-verbs\-4th\-conjugation"/"conj22.htm#sect35"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/clauses\-and\-sentences"/"syntax.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/clauses\-characteristic"/"subordinate-clauses.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/clauses\-proviso"/"subordinate-clauses.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/combinations"/"pronunciation.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/commands\-indirect\-discourse"/"indirect-discourse.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/comparatives\-and\-superlatives"/"syntax.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/comparison\-adjectives"/"adjective-declensions.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/comparison\-adverbs"/"adverbs.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/concessive\-clauses"/"subordinate-clauses.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conditional\-relative"/"conditionals.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conditional\-sentences"/"conditionals.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/condition\-omitted"/"conditionals.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conditions\-indirect\-discourse"/"indirect-discourse.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conjunctions"/"conjunctions.htm#222"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conjunctions\#coordinate"/"conjunctions.htm#coordinate"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/conjunctions\#subordinate"/"conjunctions.htm#subordinate"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/correlatives"/"pronouns.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/cum\-clauses"/"subordinate-clauses.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/cum\-clauses\#cum\-causal"/"subordinate-clauses.htm#cum-causal"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/cum\-clauses\#cum\-temporal"/"subordinate-clauses.htm#cum-temporal"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/dative"/"caseuses.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/dative\-agent"/"caseuses.htm#sect15"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/dative\-indirect\-object\-intransitive\-verbs"/"caseuses.htm#sect11"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/dative\-purpose"/"caseuses.htm#sect19"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/declamatory\-sentences\-indirect\-discourse"/"indirect-discourse.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/declension\-cardinals\-and\-ordinals"/"numerals.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/declension\-comparatives"/"adjective-declensions.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/defective\-verbs"/"conj27.htm#sect31"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/deliberative\-subjunctive"/"moods-tenses.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/demonstrative\-pronouns"/"syntax.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/demonstrative\-pronouns\-paradigms"/"pronouns.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/deponent\-verbs"/"conj20.htm#sect24"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-adjectives"/"wordformation.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-adjectives\#nominal\-adjecives"/"wordformation.htm#nominal-adjectives"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-adjectives\#nominal\-adjectives"/"wordformation.htm#nominal-adjectives"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-adjectives\#nominal\-edjectives"/"wordformation.htm#nominal-adjectives"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-adjectives\#verbal\-adjectives"/"wordformation.htm#verbal-adjectives"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-prepositions"/"prepositions.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-tenses"/"moods-tenses.htm#sect14"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-verbs"/"wordformation.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-verbs\#"/"wordformation.htm#verbs-from-other-verbs"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-verbs\#intensives\-or\-iteratives"/"wordformation.htm#intensives-or-iteratives"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-verbs\#denominative\-verbs"/"wordformation.htm#denominative-verbs"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/derivation\-verbs\#verbs\-from\-other\-verbs"/"wordformation.htm#verbs-from-other-verbs"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/disguised\-conditionals"/"conditionals.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/distributives"/"numerals.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/dum\-dōnec\-and\-quoad"/"subordinate-clauses.htm#sect12"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/epistolary\-tenses"/"moods-tenses.htm#sect20"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/ethical\-dative"/"caseuses.htm#sect17"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/formation\-adjectives"/"adjective-declensions.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/formation\-supine"/"conj11.htm#sect14"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/formation\-words"/"wordformation.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/forms\-participle"/"conj2.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/future\-participle"/"participles.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/gender"/"inflection.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/general\-conditions"/"conditionals.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/general\-rules\-quantity"/"quantity.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/general\-rules\-quantity\#quantity\-syllables"/"quantity.htm#quantity-syllables"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/gerund\-and\-supine"/"conj3.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/glossary"/"glossary.htm"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/glossary\#rhetorical\-figures"/"glossary.htm#rhetorical-figures"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/hortatory\-subjunctive"/"moods-tenses.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/imperative"/"moods-tenses.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/imperative\#prohibition"/"moods-tenses.htm#prohibition"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/imperfect\-tense"/"moods-tenses.htm#sect16"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/important\-rules\-syntax"/"rules-syntax.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/indefinite\-pronouns"/"syntax.htm#sect14"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/indicative\-mood"/"moods-tenses.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/indicative\-quod"/"subordinate-clauses.htm#sect17"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/indirect\-questions"/"subordinate-clauses.htm#sect18"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/infinitive"/"moods-tenses.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/infinitive\-noun"/"moods-tenses.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/inflected\-language"/"inflection.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/interjections"/"interjections.htm"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/intermediate\-clauses"/"indirect-discourse.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/intermediate\-clauses\#informal\-indirect\-discourse"/"indirect-discourse.htm#informal-indirect-discourse"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/intermediate\-clauses\#subjunctive\-integral\-part"/"indirect-discourse.htm#subjunctive-integral-part"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-and\-defective\-comparison\-adjectives"/"adjective-declensions.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-derivatives"/"wordformation.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregularities\-and\-special\-uses\-adjectives"/"adjective-declensions.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-verbs\-compounds\-sum"/"conj21.htm#sect26"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-verbs\-dō\-eō\-and\-adeō"/"conj25.htm#sect29"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-verbs\-ferō\-and\-edō"/"conj24.htm#sect28"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/irregular\-verbs\-volō\-nōlō\-mālō"/"conj23.htm#sect27"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/kindred\-forms"/"pronunciation.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/measures"/"measurement.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/measures\#measures\-capacity"/"measurement.htm#measures-capacity"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/measures\#measures\-length"/"measurement.htm#measures-length"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/measures\#measures\-weight"/"measurement.htm#measures-weight"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/negative\-particles"/"syntax.htm#sect18"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/nominative"/"caseuses.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/nouns\-adjective\-suffixes"/"wordformation.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/nouns\-defective\-cases"/"noun-declensions.htm#sect29"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/nouns\-lacking\-singular"/"noun-declensions.htm#sect28"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/numeral\-adverbs"/"numerals.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/optative\-subjunctive"/"moods-tenses.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/order\-words"/"rules-syntax.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/origins\-quantity"/"quantity.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/orthography"/"pronunciation.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-numerals"/"numerals.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive"/"moods-tenses.htm#sect13"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive\#exclamatory\-infinitive"/"moods-tenses.htm#exclamatory-infinitive"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive\#exclamatory\-infinitives"/"moods-tenses.htm#exclamatory-infinitive"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive\#historical\-infinitive"/"moods-tenses.htm#historical-infinitive"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive\#infinitive\-purpose"/"moods-tenses.htm#infinitive-purpose"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/other\-uses\-infinitive\#peculiar\-infinitives"/"moods-tenses.htm#peculiar-infinities"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/parallel\-forms"/"conj19.htm#sect23"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/particles"/"particles.htm"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/particular\-conditions"/"conditionals.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/particular\-conditions\#future"/"conditionals.htm#future"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/parts\-speech"/"speech.htm"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/peculiar\-genitives"/"caseuses.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/peculiarities"/"conj13.htm#sect17"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/perfect\-stem"/"conj10.htm#sect13"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/perfect\-system"/"conj6.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/perfect\-tense"/"moods-tenses.htm#sect18"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/periphrastic\-conjugations"/"conj20.htm#sect25"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/personal\-endings"/"conj3.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/personal\-pronouns"/"syntax.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/personal\-pronouns\-paradigm"/"pronouns.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/phonetic\-change"/"pronunciation.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/pluperfect\-and\-future\-perfect\-tenses"/"moods-tenses.htm#sect19"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/pluperfect\-and\-future\-perfect\-tenses\#future\-perfect"/"moods-tenses.htm#future-perfect"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/possesive\-pronouns"/"syntax.htm#sect12"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/possessive\-pronouns\-paradigm"/"pronouns.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/potential\-subjunctive"/"moods-tenses.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/present\-stem"/"conj9.htm#sect12"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/present\-system"/"conj5.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/present\-tense"/"moods-tenses.htm#sect15"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/pronouns"/"syntax.htm#sect8"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/pronouns\-classes"/"pronouns.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/protasis\-and\-apodasis"/"conditionals.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/protasis\-and\-apodosis"/"conditionals.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/purpose\-clauses"/"subordinate-clauses.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/quantity"/"pronunciation.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/quantity\-derivatives"/"quantity.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/quantity\-perfects\-and\-perfect\-participles"/"quantity.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/quantity\-syllables"/"pronunciation.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/questions"/"syntax.htm#sect19"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/questions\#double\-questions"/"syntax.htm#double-questions"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/questions\-indirect\-discourse"/"indirect-discourse.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/questions\#question\-and\-answer"/"syntax.htm#question-and-answer"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/quīn\-and\-quōminus"/"subordinate-clauses.htm#sect13"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/reckoning\-time"/"measurement.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/reflexive\-pronouns"/"syntax.htm#sect11"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/reflexive\-pronouns\-paradigm"/"pronouns.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/relative\-interrogative\-and\-indefinite\-pronouns"/"pronouns.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/relative\-pronouns"/"syntax.htm#sect13"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/relative\-pronouns\#antecedent\-of\-relative"/"syntax.htm#antecedent-of-relative"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/relative\-pronouns\#special\-uses\-relative"/"syntax.htm#special-uses-relative"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/result\-clauses"/"subordinate-clauses.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/roots\-and\-stems"/"wordformation.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/roots\-stems\-and\-bases"/"inflection.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/rules\-noun\-declension"/"inflection.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/sequence\-tenses"/"moods-tenses.htm#sect22"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/si\-and\-its\-compoounds"/"subordinate-clauses.htm#sect2"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/stems"/"conj3.htm#sect6"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/structure\-period"/"rules-syntax.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/subjunctive\-mood"/"moods-tenses.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/subordinate\-clauses\-indirect\-discourse"/"indirect-discourse.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/substantive\-clauses"/"subordinate-clauses.htm#sect14"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/substantive\-clauses\-purpose"/"subordinate-clauses.htm#sect15"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/substantive\-clauses\-purpose\#substantive\-purpose\-passive\-verbs"/"subordinate-clauses.htm#substantive-purpose-passive-verbs"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/sum"/"conj7.htm#sect10"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/supine"/"participles.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/syllables"/"pronunciation.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/synopsis\-verb"/"conj13.htm#sect16"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/syntax\-introductory\-note"/"syntax.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/temporal\-clauses"/"subordinate-clauses.htm#sect9"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/tenses"/"conj3.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/tenses\-infinitive"/"moods-tenses.htm#sect23"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/tenses\-infinitive\-indirect\-discourse"/"indirect-discourse.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/tenses\-"/"moods-tenses.htm#sect21"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/tenses\-subjunctive\-indirect\-discourse"/"indirect-discourse.htm#sect5"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/uses\-cardinals\-and\-ordinals"/"numerals.htm#sect4"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/uses\-conjunctions"/"syntax.htm#sect17"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/variable\-nouns"/"noun-declensions.htm#sect30"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verb\-conjugations"/"conj1.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verb\-endings"/"conj4.htm#sect7"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verb\-moods\-and\-tenses"/"moods-tenses.htm#sect1"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verbs\-and\-subjects"/"syntax.htm#sect15"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verbs\-and\-subjects\#double\-collective\-subject"/"syntax.htm#double-collective-subject"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verbs\-and\-subjects\#omission\-subject\-verb"/"syntax.htm#omission-subject-verb"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/verbs\-and\-subjects\#ommission\-subject\-verb"/"syntax.htm#omission-subject-verb"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/vocative"/"caseuses.htm#sect3"/g' fullindex.htm
perl -i -p -e 's/"http\:\/\/dcc\.dickinson\.edu\/grammar\/latin\/vowel\-and\-consonant\-pronunciation"/"pronunciation.htm#sect5"/g' fullindex.htm
